'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Room, RoomEvent, Track, createLocalAudioTrack, createLocalScreenTracks, createLocalVideoTrack, type LocalTrack, type RemoteTrack, type RemoteTrackPublication, type RemoteParticipant, type LocalTrackPublication } from 'livekit-client';

type Participant = { id: string; role: 'host' | 'viewer'; displayName?: string };
type Grant = { participantId?: string; enabled?: boolean; ownGrant?: Permissions; canPublishAudio?: boolean; canPublishVideo?: boolean; canPublishScreen?: boolean; canSubscribe?: boolean };
type Permissions = { canPublishAudio: boolean; canPublishVideo: boolean; canPublishScreen: boolean; canSubscribe: boolean };
type SocketLike = { on: (event: string, cb: (value: unknown) => void) => void; off: (event: string, cb: (value: unknown) => void) => void; emit: (event: string, body: unknown, ack?: (value: unknown) => void) => void };
type Publication = LocalTrackPublication | LocalTrackPublication[] | undefined;
type Tile = { id: string; participantId: string; name: string; track: RemoteTrack | LocalTrackPublication['track']; kind: 'video' | 'audio'; local: boolean; source?: string };
export const conferenceTokenHeaders = (token: string) => ({ Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' });
export const limitConferenceTiles = <T,>(tiles: T[], max = 6) => tiles.slice(0, max);
export const livekitUrl = () => (typeof window !== 'undefined' && (window as Window & { __WATCH_WITH_ME_LIVEKIT_URL?: string }).__WATCH_WITH_ME_LIVEKIT_URL) || process.env.NEXT_PUBLIC_LIVEKIT_URL || '';
export const livekitErrorReason = (error: unknown, production = false) => { const message = error instanceof Error ? error.message : 'unknown error'; return !production && (process.env.NODE_ENV === 'development' || process.env.NODE_ENV === 'test') ? `LiveKit: ${message}` : 'تعذر الاتصال بـ LiveKit.'; };
export const shouldApplyConferenceStatus = (requestGeneration: number, latestGeneration: number) => requestGeneration === latestGeneration;
export const CONFERENCE_POLICY_ACK_TIMEOUT_MS = 5000;
export const localPublicationTileId = (participantId: string, publication: { source: string; trackSid?: string; sid?: string }) => `${participantId}:${publication.source}:${publication.trackSid ?? publication.sid}`;
export const remotePublicationTileId = (participantId: string, publication: { trackSid?: string; sid?: string }) => `${participantId}:${publication.trackSid ?? publication.sid}`;
export const LOCAL_MEDIA_TIMEOUT_MS = 5000;
export const LOCAL_MEDIA_STABILIZATION_MS = 3000;
export const shouldRepublishLocalTrack = (retained: LocalTrack | undefined, publicationTrack: LocalTrack | undefined, intentionalRemoval: boolean, pending: boolean) => {
  void publicationTrack;
  return Boolean(retained && retained.mediaStreamTrack.readyState === 'live' && !intentionalRemoval && !pending);
};
export const deferred = <T,>() => { let resolve!: (value: T) => void; let reject!: (reason?: unknown) => void; const promise = new Promise<T>((res, rej) => { resolve = res; reject = rej; }); return { promise, resolve, reject }; };
export const localProvisionalTileId = (participantId: string, source: string, track: { sid?: string; kind?: string }) => `${participantId}:${source}:${track.sid ?? 'pending'}`;
export const conferenceMediaSources = [Track.Source.Microphone, Track.Source.Camera, Track.Source.ScreenShare, Track.Source.ScreenShareAudio] as const;
export const revokeLocalTracks = (tracks: Map<string, LocalTrack>, unpublish: (track: LocalTrack) => void) => {
  for (const source of conferenceMediaSources) { const track = tracks.get(source); if (!track) continue; unpublish(track); track.stop(); tracks.delete(source); }
};
const conferenceTrace = (...values: unknown[]) => { void values; };

function TrackView({ tile, muted }: { tile: Tile; muted: boolean }) {
  const ref = useRef<HTMLVideoElement & HTMLAudioElement>(null);
  useEffect(() => {
    const element = ref.current; const track = tile.track;
    if (!element || !track) return;
    track.attach(element); if ('muted' in element) element.muted = muted;
    return () => { track.detach(element); };
  }, [tile.track, muted]);
  return tile.kind === 'video' ? <video ref={ref} autoPlay playsInline aria-label={tile.name} data-participant-id={tile.participantId} data-media-source={tile.source} /> : <audio ref={ref} autoPlay aria-label={tile.name} data-participant-id={tile.participantId} data-media-source={tile.source} />;
}

export function ConferencePanel({ socket, tokenUrl, token, currentParticipant, participants }: {
  socket: SocketLike | null; tokenUrl: string; token: string; currentParticipant: Participant | null; participants: Participant[];
}) {
  const isHost = currentParticipant?.role === 'host'; const selfId = currentParticipant?.id;
  const roomRef = useRef<Room | null>(null); const tracksRef = useRef(new Map<string, Tile>());
  const localTracksRef = useRef(new Map<string, LocalTrack>()); const localPublicationsRef = useRef(new Map<string, LocalTrackPublication>()); const localPendingRef = useRef(new Set<string>()); const localPublicationWaitersRef = useRef(new Map<string, ReturnType<typeof deferred<LocalTrackPublication>>>()); const localUnpublishWaitersRef = useRef(new Map<string, ReturnType<typeof deferred<LocalTrackPublication>>>()); const intentionalRemovalRef = useRef(new Set<string>()); const mediaOperationRef = useRef(Promise.resolve());
  const statusGeneration = useRef(0); const statusAbort = useRef<AbortController | null>(null); const policyPendingRef = useRef(false);
  const [connected, setConnected] = useState(false); const [permissions, setPermissions] = useState<Permissions>({ canPublishAudio: Boolean(isHost), canPublishVideo: Boolean(isHost), canPublishScreen: Boolean(isHost), canSubscribe: Boolean(isHost) }); const [policy, setPolicy] = useState(false); const [policyPending, setPolicyPending] = useState(false); const [pendingPolicyValue, setPendingPolicyValue] = useState(false);
  const [tiles, setTiles] = useState<Tile[]>([]); const [remoteMuted, setRemoteMuted] = useState<Set<string>>(new Set()); const [error, setError] = useState(''); const [status, setStatus] = useState('');
  const [mic, setMic] = useState(false); const [camera, setCamera] = useState(false); const [screen, setScreen] = useState(false); const [systemAudio, setSystemAudio] = useState(false); const [mediaPending, setMediaPending] = useState<Set<string>>(new Set());
  const updateTiles = useCallback(() => setTiles(Array.from(tracksRef.current.values()).slice(0, 12)), []);
  const removeParticipantTracks = useCallback((participantId: string) => { for (const [id, tile] of tracksRef.current) if (tile.participantId === participantId) tracksRef.current.delete(id); updateTiles(); }, [updateTiles]);
  const cleanup = useCallback(async () => { const room = roomRef.current; if (!room) return; for (const [source, track] of localTracksRef.current) { try { await room.localParticipant.unpublishTrack(track); } catch { /* already unpublished */ } track.stop(); localTracksRef.current.delete(source); localPublicationsRef.current.delete(source); } localPendingRef.current.clear(); setMediaPending(new Set()); for (const tile of tracksRef.current.values()) tile.track?.detach(); tracksRef.current.clear(); await room.disconnect(); roomRef.current = null; setTiles([]); setConnected(false); setMic(false); setCamera(false); setScreen(false); }, []);

  const removeLocalSource = useCallback((participantId: string, source: string) => { const track = localTracksRef.current.get(source); const room = roomRef.current; if (!track || !room) return; intentionalRemovalRef.current.add(source); const operation = async () => { const publication = localPublicationsRef.current.get(source); const waiter = deferred<LocalTrackPublication>(); localUnpublishWaitersRef.current.set(source, waiter); try { await room.localParticipant.unpublishTrack(track); if (publication) await Promise.race([waiter.promise, new Promise(resolve => window.setTimeout(resolve, LOCAL_MEDIA_TIMEOUT_MS))]); } finally { localUnpublishWaitersRef.current.delete(source); localTracksRef.current.delete(source); localPublicationsRef.current.delete(source); track.stop(); for (const [id, tile] of tracksRef.current) if (tile.local && tile.participantId === participantId && (tile.source === source || tile.track === track)) { tile.track?.detach(); tracksRef.current.delete(id); } updateTiles(); intentionalRemovalRef.current.delete(source); } }; const queued = mediaOperationRef.current.then(operation, operation); mediaOperationRef.current = queued.catch(() => undefined); }, [updateTiles]);
  const cleanupPublished = useCallback(() => { const room = roomRef.current; conferenceTrace('cleanupPublished entry', { selfId, refs: [...localTracksRef.current.entries()].map(([source, track]) => ({ source, id: track.mediaStreamTrack.id, readyState: track.mediaStreamTrack.readyState })), publications: [...localPublicationsRef.current.entries()].map(([source, publication]) => ({ source, trackSid: publication.trackSid, publicationSource: publication.source })) }); const published = new Set(Array.from(localPublicationsRef.current.values()).map(publication => publication.track)); revokeLocalTracks(localTracksRef.current, track => { if (room && published.has(track)) void room.localParticipant.unpublishTrack(track).catch(() => undefined); }); localPublicationsRef.current.clear(); for (const [id, tile] of tracksRef.current) if (tile.local) { tile.track?.detach(); tracksRef.current.delete(id); } updateTiles(); setMic(false); setCamera(false); setScreen(false); }, [selfId, updateTiles]);
  useEffect(() => {
    if (!socket) return; const onGrant = (value: unknown) => { statusGeneration.current++; const grant = value as Grant; conferenceTrace('conference.grants', { selfId, target: grant.participantId, payload: grant }); if (grant.participantId !== selfId) return; const next = { canPublishAudio: grant.canPublishAudio === true, canPublishVideo: grant.canPublishVideo === true, canPublishScreen: grant.canPublishScreen === true, canSubscribe: grant.canSubscribe !== false }; conferenceTrace('grant matched', { selfId, next }); setPermissions(next); if (!next.canPublishAudio && !next.canPublishVideo && !next.canPublishScreen) cleanupPublished(); }; const onPolicy = (value: unknown) => { statusGeneration.current++; const state = value as Grant; if (typeof state.enabled === 'boolean') { if (!isHost || !policyPendingRef.current) setPolicy(state.enabled); if (state.enabled && !isHost) setStatus('يمكنك الانضمام إلى المؤتمر الآن.'); } if (state.ownGrant) setPermissions(state.ownGrant); };
    socket.on('conference.grants', onGrant); socket.on('conference.policy.changed', onPolicy); return () => { socket.off('conference.grants', onGrant); socket.off('conference.policy.changed', onPolicy); };
  }, [socket, selfId, cleanupPublished, isHost]);
  useEffect(() => () => { void cleanup(); }, [cleanup]);
  useEffect(() => { if (!tokenUrl || !token) return; statusAbort.current?.abort(); const abort = new AbortController(); statusAbort.current = abort; const requestGeneration = statusGeneration.current; const statusUrl = tokenUrl.replace(/\/token$/, '/status'); void fetch(statusUrl, { headers: conferenceTokenHeaders(token), signal: abort.signal }).then(r => r.ok ? r.json() : null).then((value: Grant | null) => { if (!value || abort.signal.aborted || !shouldApplyConferenceStatus(requestGeneration, statusGeneration.current)) return; setPolicy(value.enabled === true); if (value.ownGrant) setPermissions(value.ownGrant); }).catch(() => undefined); return () => abort.abort(); }, [tokenUrl, token, socket, isHost]);
   const addTrack = useCallback((track: RemoteTrack | LocalTrackPublication['track'], participantId: string, name: string, local: boolean, publication?: LocalTrackPublication | RemoteTrackPublication, explicitSource?: string) => { if (!track) return; const kind = track.kind === Track.Kind.Video ? 'video' : 'audio'; const source = explicitSource ?? publication?.source ?? track.source; if (local && source) for (const [existingId, existingTile] of tracksRef.current) if (existingTile.local && existingTile.participantId === participantId && existingTile.source === source) { existingTile.track?.detach(); tracksRef.current.delete(existingId); } const id = local && publication ? localPublicationTileId(participantId, publication) : !local && publication ? remotePublicationTileId(participantId, publication) : local && source ? localProvisionalTileId(participantId, source, track) : `${participantId}:${source ?? track.sid ?? track.kind}`; const tile = { id, participantId, name, track, kind, local, source } as Tile; tracksRef.current.set(id, tile); updateTiles(); }, [updateTiles]);
  const addLocalPublication = useCallback((participantId: string, publication: Publication) => { for (const item of publication ? (Array.isArray(publication) ? publication : [publication]) : []) if (item.track) addTrack(item.track, participantId, 'أنت', true, item); }, [addTrack]);
  const addLocalPublicationAfterPublish = useCallback((room: Room, publication: LocalTrackPublication) => { addLocalPublication(room.localParticipant.identity, publication); if (!publication.track) queueMicrotask(() => addLocalPublication(room.localParticipant.identity, publication)); }, [addLocalPublication]);
  const connect = async () => {
    if (!isHost && !policy) { setError('لم يفعّل المضيف المؤتمر بعد.'); return; }
     try { setError(''); const response = await fetch(tokenUrl, { method: 'POST', headers: conferenceTokenHeaders(token) }); if (!response.ok) throw new Error('token'); const data = await response.json() as { token?: string; iceServers?: RTCIceServer[] }; if (!data.token) throw new Error('token'); const relayOnly = process.env.NEXT_PUBLIC_LIVEKIT_RELAY_ONLY === 'true'; const room = new Room({ adaptiveStream: true, dynacast: true });
         const reconcileRemotePublication = (publication: RemoteTrackPublication, participant: RemoteParticipant) => { if (publication.track) addTrack(publication.track, participant.identity, participant.identity, false, publication); else void publication.setSubscribed(true); };
        const syncRemoteTracks = () => { for (const participant of room.remoteParticipants.values()) for (const publication of participant.trackPublications.values()) reconcileRemotePublication(publication, participant); updateTiles(); };
        room.on(RoomEvent.TrackSubscribed, (track: RemoteTrack, publication: RemoteTrackPublication, participant: RemoteParticipant) => addTrack(track, participant.identity, participant.identity, false, publication));
        room.on(RoomEvent.TrackPublished, (publication: RemoteTrackPublication, participant: RemoteParticipant) => reconcileRemotePublication(publication, participant));
        room.on(RoomEvent.TrackUnpublished, (publication: RemoteTrackPublication, participant: RemoteParticipant) => { const id = remotePublicationTileId(participant.identity, publication); window.setTimeout(() => { const replacement = participant.getTrackPublication(publication.source); if (replacement && replacement !== publication) { reconcileRemotePublication(replacement, participant); return; } tracksRef.current.get(id)?.track?.detach(); tracksRef.current.delete(id); updateTiles(); }, 100); });
        room.on(RoomEvent.TrackUnsubscribed, (track: RemoteTrack, publication: RemoteTrackPublication, participant: RemoteParticipant) => { conferenceTrace('TrackUnsubscribed', { participant: participant.identity, trackId: track.mediaStreamTrack.id, trackSid: publication.trackSid, source: publication.source, status: publication.subscriptionStatus }); track.detach(); if (track.mediaStreamTrack.readyState === 'ended') { for (const [id, tile] of tracksRef.current) if (tile.track === track) tracksRef.current.delete(id); updateTiles(); } else { window.setTimeout(() => { void publication.setSubscribed(true); }, 0); } });
       room.on(RoomEvent.ParticipantDisconnected, (participant: RemoteParticipant) => removeParticipantTracks(participant.identity));
         room.on(RoomEvent.LocalTrackPublished, (publication: LocalTrackPublication) => { localPublicationsRef.current.set(publication.source, publication); localPublicationWaitersRef.current.get(publication.source)?.resolve(publication); addLocalPublicationAfterPublish(room, publication); });
         room.on(RoomEvent.LocalTrackUnpublished, (publication: LocalTrackPublication) => { localUnpublishWaitersRef.current.get(publication.source)?.resolve(publication); publication.track?.detach(); localPublicationsRef.current.delete(publication.source); localTracksRef.current.delete(publication.source); localPendingRef.current.delete(publication.source); setMediaPending(old => { const next = new Set(old); next.delete(publication.source); return next; }); for (const [id, tile] of tracksRef.current) if (tile.local && tile.participantId === room.localParticipant.identity && tile.source === publication.source) { tile.track?.detach(); tracksRef.current.delete(id); } updateTiles(); if (publication.source === Track.Source.Microphone) setMic(false); if (publication.source === Track.Source.Camera) setCamera(false); if (publication.source === Track.Source.ScreenShare || publication.source === Track.Source.ScreenShareAudio) setScreen(false); });
        room.on(RoomEvent.ParticipantConnected, syncRemoteTracks); room.on(RoomEvent.Disconnected, () => { setConnected(false); setStatus('انقطع اتصال LiveKit'); });
        const url = livekitUrl(); if (!url) throw new Error('missing LiveKit URL'); await room.connect(url, data.token, { rtcConfig: { iceTransportPolicy: relayOnly ? 'relay' : 'all', iceServers: data.iceServers ?? [] } }); roomRef.current = room; setConnected(true); setStatus('تم الاتصال');
       syncRemoteTracks();
    } catch (reason) { setError(livekitErrorReason(reason)); }
  };
    const publishLocal = async (source: string, track: LocalTrack, setEnabled: (value: boolean) => void) => { const room = roomRef.current; if (!room || localPendingRef.current.has(source)) { track.stop(); return; } localPendingRef.current.add(source); setMediaPending(old => new Set(old).add(source)); localTracksRef.current.set(source, track); addTrack(track, room.localParticipant.identity, 'أنت', true, undefined, source); const operation = async () => { const waiter = deferred<LocalTrackPublication>(); localPublicationWaitersRef.current.set(source, waiter); let publish!: Promise<LocalTrackPublication>; const lateFailure = (reason: unknown) => { if (localTracksRef.current.get(source) !== track) return; localTracksRef.current.delete(source); localPublicationsRef.current.delete(source); track.stop(); removeLocalSource(room.localParticipant.identity, source); setEnabled(false); setError('تعذر نشر الوسائط.'); void reason; }; try { publish = room.localParticipant.publishTrack(track, { source: source as Track.Source }); const stabilization = new Promise<{ stable: true }>(resolve => window.setTimeout(() => resolve({ stable: true }), LOCAL_MEDIA_STABILIZATION_MS)); const result = await Promise.race([publish.then(publication => ({ publication }), error => { throw error; }), waiter.promise.then(publication => ({ publication })), stabilization]); if ('stable' in result) { if (roomRef.current !== room || localTracksRef.current.get(source) !== track || track.mediaStreamTrack.readyState !== 'live') throw new Error('media_not_stable'); void publish.catch(reason => { if (roomRef.current === room && localTracksRef.current.get(source) === track && track.mediaStreamTrack.readyState === 'live') conferenceTrace('late local publish rejection', { source, reason }); }); setEnabled(true); } else { localPublicationsRef.current.set(source, result.publication); for (const [id, tile] of tracksRef.current) if (tile.track === track && tile.source === source) tracksRef.current.delete(id); addTrack(track, room.localParticipant.identity, 'أنت', true, result.publication); setEnabled(true); } } catch (reason) { lateFailure(reason); } finally { localPublicationWaitersRef.current.delete(source); localPendingRef.current.delete(source); setMediaPending(old => { const next = new Set(old); next.delete(source); return next; }); } }; const queued = mediaOperationRef.current.then(operation, operation); mediaOperationRef.current = queued.catch(() => undefined); return queued; };
  const toggleMic = async () => { const room = roomRef.current; if (!room || localPendingRef.current.has(Track.Source.Microphone)) return; if (mic) { removeLocalSource(room.localParticipant.identity, Track.Source.Microphone); setMic(false); return; } try { await publishLocal(Track.Source.Microphone, await createLocalAudioTrack(), setMic); } catch { setError('تعذر الوصول إلى الميكروفون.'); } };
  const toggleCamera = async () => { const room = roomRef.current; if (!room || localPendingRef.current.has(Track.Source.Camera)) return; if (camera) { removeLocalSource(room.localParticipant.identity, Track.Source.Camera); setCamera(false); return; } try { await publishLocal(Track.Source.Camera, await createLocalVideoTrack(), setCamera); } catch { setError('تعذر الوصول إلى الكاميرا.'); } };
  const toggleScreen = async () => { const room = roomRef.current; if (!room || localPendingRef.current.has(Track.Source.ScreenShare)) return; if (screen) { removeLocalSource(room.localParticipant.identity, Track.Source.ScreenShare); removeLocalSource(room.localParticipant.identity, Track.Source.ScreenShareAudio); setScreen(false); return; } try { const tracks = await createLocalScreenTracks({ audio: systemAudio }); for (const track of tracks) await publishLocal(track.kind === Track.Kind.Audio ? Track.Source.ScreenShareAudio : Track.Source.ScreenShare, track, setScreen); setScreen(true); } catch { removeLocalSource(room.localParticipant.identity, Track.Source.ScreenShare); removeLocalSource(room.localParticipant.identity, Track.Source.ScreenShareAudio); setScreen(false); setError('تعذرت مشاركة الشاشة أو صوت النظام.'); } };
  const command = (event: string, participantId: string, confirmText: string, extra: Record<string, unknown> = {}) => { if (!socket || !window.confirm(confirmText)) return; socket.emit(event, { participantId, ...extra }, value => { if ((value as { error?: string })?.error) setError(`تعذر تنفيذ العملية: ${(value as { error: string }).error}`); else setStatus('تم تنفيذ العملية'); }); };
  return <section className="conference-panel" aria-label="الفيديو الجماعي"><h2>الفيديو الجماعي <small>LiveKit · {Math.min(6, new Set(tiles.map(t => t.participantId)).size)}/6</small></h2><p className="live-note">لا تُطلب صلاحيات الأجهزة قبل النقر. موافقة المضيف تمنحك القدرة فقط؛ لا يمكن تشغيل جهاز مشارك آخر قسراً.</p>{error && <p role="alert" className="error">{error}</p>}{status && <p role="status" aria-live="polite">{status}</p>}
       {isHost && <label><input type="checkbox" checked={policyPending ? pendingPolicyValue : policy} disabled={policyPending || !socket} onChange={e => { const value = e.target.checked; const previous = policy; if (!socket) { setError('تعذر الاتصال بالخادم لتحديث سياسة المؤتمر.'); return; } setPendingPolicyValue(value); policyPendingRef.current = true; setPolicyPending(true); statusGeneration.current++; let settled = false; const finish = (next: { error?: string } | undefined) => { if (settled) return; settled = true; window.clearTimeout(timeout); policyPendingRef.current = false; setPolicyPending(false); if (next?.error) { setPolicy(previous); setError('تعذر تحديث سياسة المؤتمر؛ أُعيدت الحالة السابقة.'); } else { setPolicy(value); setStatus('تم تحديث سياسة المؤتمر.'); } }; const timeout = window.setTimeout(() => { statusGeneration.current++; finish({ error: 'ack_timeout' }); }, CONFERENCE_POLICY_ACK_TIMEOUT_MS); socket.emit('conference.policy.changed', { enabled: value }, v => finish(v as { error?: string } | undefined)); }} /> تفعيل المؤتمر للمشاهدين</label>}
       {!connected ? <button type="button" onClick={() => void connect()} disabled={!isHost && !policy}>انضمام إلى الفيديو</button> : <><div className="conference-grid" aria-label="مشاركو المؤتمر">{limitConferenceTiles(tiles).map(tile => <div className="conference-tile" key={tile.id}><TrackView tile={tile} muted={tile.local || (!tile.local && remoteMuted.has(tile.participantId))} /><span>{tile.name}</span>{!tile.local && tile.kind === 'video' && <button type="button" onClick={() => setRemoteMuted(old => { const next = new Set(old); if (next.has(tile.participantId)) next.delete(tile.participantId); else next.add(tile.participantId); return next; })}>{remoteMuted.has(tile.participantId) ? 'إلغاء الكتم المحلي' : 'كتم محلي'}</button>}</div>)}</div><button type="button" disabled={!permissions.canPublishAudio || mediaPending.size > 0} onClick={() => void toggleMic()}>{mic ? 'كتم الميكروفون' : 'تشغيل الميكروفون'}</button><button type="button" disabled={!permissions.canPublishVideo || mediaPending.size > 0} onClick={() => void toggleCamera()}>{camera ? 'إيقاف الكاميرا' : 'تشغيل الكاميرا'}</button><label><input type="checkbox" disabled={!permissions.canPublishScreen || mediaPending.size > 0} checked={systemAudio} onChange={e => setSystemAudio(e.target.checked)} /> مشاركة صوت النظام</label><button type="button" disabled={!permissions.canPublishScreen || mediaPending.size > 0} onClick={() => void toggleScreen()}>{screen ? 'إيقاف مشاركة الشاشة' : 'مشاركة الشاشة'}</button><button type="button" onClick={() => void cleanup()}>مغادرة الفيديو</button></>}
    {isHost && <div className="participant-controls"><h3>صلاحيات المشاركين</h3>{participants.filter(p => p.role === 'viewer').map(p => <div key={p.id}><strong>{p.displayName || p.id}</strong><button type="button" onClick={() => command('conference.grant', p.id, `السماح لـ ${p.displayName || p.id}؟`, { canPublishScreen: policy })}>سماح</button><button type="button" onClick={() => command('conference.revoke', p.id, `سحب صلاحية ${p.displayName || p.id}؟`)}>سحب</button><button type="button" onClick={() => command('moderation.mute', p.id, `كتم ${p.displayName || p.id}؟`)}>كتم</button><button type="button" onClick={() => command('moderation.kick', p.id, `طرد ${p.displayName || p.id}؟`)}>طرد</button></div>)}</div>}
  </section>;
}
